# Generated by Django 3.2 on 2021-10-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_info', '0002_info_info_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='update_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
