# Generated by Django 3.2 on 2021-10-01 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search_info', '0003_alter_info_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
