# Generated by Django 3.2 on 2021-10-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_info', '0004_alter_info_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='infos',
            field=models.ManyToManyField(to='search_info.Info'),
        ),
    ]
