# Generated by Django 3.2 on 2021-10-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_info', '0005_tag_infos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='infos',
        ),
        migrations.AddField(
            model_name='info',
            name='tags',
            field=models.ManyToManyField(to='search_info.Tag'),
        ),
    ]
