# Generated by Django 3.2 on 2021-10-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_info', '0006_auto_20211016_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info_tag',
        ),
    ]
