# Generated by Django 3.2 on 2021-10-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_info', '0007_delete_info_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='tags',
            field=models.ManyToManyField(related_name='tag_text', to='search_info.Tag'),
        ),
    ]
